name: build-x86-64-openwrt

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: "选择 OpenWrt 版本 (参考官方 Releases)"
        required: false
        default: "25.12.0"
        type: choice
        options:
          - "25.12.0"
          - "24.10.5"
          - "23.05.6"
          - "snapshot"
      custom_router_ip:
        description: "请设置路由器的管理地址(仅对多网口路由器有效) 格式:192.168.x.1 或 10.x.x.1"
        required: true
        default: "192.168.1.1"
      profile:
        description: '请输入要编译固件大小 单位(MB)'
        required: true
        default: '1024'
      include_docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "是否配置PPPoE拨号信息?"
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: "宽带账号 (若启用PPPoE)"
        required: false
      pppoe_password:
        description: "宽带密码 (若启用PPPoE)"
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        # 注意: 需确保你的仓库 x86-64 目录下有 build.sh 脚本
        run: chmod +x ${{ github.workspace }}/x86-64/build.sh

      - name: Save Custom Router IP into OpenWrt files
        run: |
          mkdir -p "${{ github.workspace }}/custom"
          echo "${{ github.event.inputs.custom_router_ip }}" > "${{ github.workspace }}/custom/custom_router_ip.txt"
          echo "您设置的路由器管理地址是:${{ github.event.inputs.custom_router_ip }}"
          
      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: 启用 PPPoE 时，必须提供账号和密码!"
              exit 1
            fi
          fi

      - name: Build OpenWrt-x86-64-efi
        run: |
          profile="${{ github.event.inputs.profile }}"
          include_docker="${{ github.event.inputs.include_docker }}"
          openwrt_version="${{ github.event.inputs.openwrt_version }}"
          echo "Building for profile: $profile, version: $openwrt_version"
          
          # 动态拉取对应版本的 ImageBuilder 镜像
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/builder/bin" \
            -v "${{ github.workspace }}/files:/builder/files" \
            -v "${{ github.workspace }}/custom:/builder/files/etc/config" \
            -v "${{ github.workspace }}/x86-64/openwrt.config:/builder/.config" \
            -v "${{ github.workspace }}/shell:/builder/shell" \
            -v "${{ github.workspace }}/x86-64/build.sh:/builder/build.sh" \
            -e PROFILE=$profile \
            -e INCLUDE_DOCKER=$include_docker \
            -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
            -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
            -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
            openwrt/imagebuilder:x86-64-${openwrt_version} /bin/bash /builder/build.sh

      - name: Create info
        run: |
          cat > ${{ github.workspace }}/router-info.md <<EOF
          ## 📡 OpenWrt 路由器后台信息
          
          - 🏠 **后台地址**: ${{ github.event.inputs.custom_router_ip }}
          - 👤 **用户名**: root
          - 🔑 **密码**: 无
          EOF

          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
            echo -e "\n#### 默认带 Docker" >> ${{ github.workspace }}/router-info.md
          else
            echo -e "\n#### 不带 Docker" >> ${{ github.workspace }}/router-info.md
          fi

      - name: Upload OpenWrt as release assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Autobuild-OpenWrt-${{ github.event.inputs.openwrt_version }}-x86-64
          body_path: ${{ github.workspace }}/router-info.md
          files: |
            ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz
            ${{ github.workspace }}/bin/targets/x86/64/*ext4-combined-efi.img.gz
          token: ${{ secrets.GITHUB_TOKEN }}
